server:
  port: 9011

#dubbo
dubbo:
  application:
    name: mall-user-web
  registry:
    protocol: zookeeper
    address: 192.168.25.110:2181
  protocol:
    name: dubbo
cas:
  server:
    host:
      url: http://localhost:8888/cas
      login_url: ${cas.server.host.url}/login
      logout_url: ${cas.server.host.url}/logout?service=https://www.baidu.com

app:
  server:
    host:
      url: http://localhost:9011
  login:
    url: /login
  logout:
    url: /logout