server:
  port: 9004

#dubbo
dubbo:
  application:
    name: mall-search-service
  registry:
    protocol: zookeeper
    address: 192.168.25.110:2181
#  scan:
#   base-package: com.beemall.
  protocol:
    name: dubbo
    port: 20882

#solr
spring:
  data:
    solr:
      host: http://127.0.0.1:8983/solr