server:
  port: 9005

#dubbo
dubbo:
  application:
    name: mall-search-service
  registry:
    protocol: zookeeper
    address: 192.168.25.110:2181
#  scan:
#   base-package: com.beemall.
  protocol:
    name: dubbo
    port: 20882

#mybatis
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.beemall.pojo
  mapperLocations: classpath:mapper/*.xml

#solr
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://127.0.0.1:8983/solr
      core: mall_core
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    password:
    port: 6379
  activemq:
    #账号密码
    user: user
    password: user
    #URL of the ActiveMQ broker.
    broker-url: tcp://192.168.25.110:61616
    #必须使用连接池
    pool:
      #启用连接池
      enabled: true
      #连接池最大连接数
      max-connections: 5
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30s
    queue: queue-solr
