server:
  port: 9002

#dubbo
dubbo:
  application:
    name: mall-manager-web
  registry:
    protocol: zookeeper
    address: 192.168.25.110:2181
#  scan:
#   base-package: com.beemall.
  protocol:
    name: dubbo
