server:
  port: 9002

#dubbo
dubbo:
  application:
    name: mall-manager-web
  registry:
    protocol: zookeeper
    address: 192.168.25.110:2181
#  scan:
#   base-package: com.beemall.
  protocol:
    name: dubbo

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5Mb
      max-request-size: 10Mb

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.25.133:22122

file:
  server:
    url: http://192.168.25.133/